server:
  port: 8081

spring:
  application:
    name: gateway-service

  ## zipkin
  zipkin:
    base-url: ${ZIPKIN_URL}

  ## routes autoconfiguration
  cloud:
    config:
      discovery:
        enabled: false
      profile: k8s
      enabled: false
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      filter:
        prefix-path:
          enabled: true

## discovery
eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true

## actuator
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessstate,cacheCheck
  endpoints:
    web:
      exposure:
        include: "*"


## circuit breaker
resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        maxAutoRetriesNextServer: 1
    instances:
      user-service:
        baseConfig: default