version: '3.8'
services:
  blog-sonar:
    image: sonarqube:8.9.1-community
    container_name: blog_sonar
    # default credentials for sonar: admin/admin
    environment:
      - sonar.forceAuthentication=true
    ports:
      - "9001:9000"
