server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: dev

  ## config server
  config:
    import: optional:configserver:http://localhost:8888

  ## routes autoconfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      filter:
        prefix-path:
          enabled: true

## discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true







