server:
  port: 8080

spring:
  application:
    name: gateway-service

  ## zipkin
  zipkin:
#    base-url: http://blog-zipkin:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin

  ## config server
  config:
    import: optional:configserver:http://blog-configuration:8888

  kafka:
    bootstrap-servers: blog-kafka:9092

  ## routes autoconfiguration
  cloud:
    config:
      profile: mock
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      filter:
        prefix-path:
          enabled: true

## discovery
eureka:
  client:
    service-url:
      defaultZone: http://blog-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

## actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


## circuit breaker
resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        maxAutoRetriesNextServer: 1
    instances:
      user-service:
        baseConfig: default








