server:
  port: 8080

spring:
  application:
    name: gateway-service


  ## zipkin
  zipkin:
    base-url: http://localhost:9411

  ## config server
  config:
    import: optional:configserver:http://localhost:8888

  ## routes autoconfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      filter:
        prefix-path:
          enabled: true

## discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

## actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


## circuit breaker
resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        maxAutoRetriesNextServer: 1
    instances:
      user-service:
        baseConfig: default








