apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: blog-gateway-service:latest
          imagePullPolicy: IfNotPresent
          name: gateway-service
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
          envFrom:
            - configMapRef:
                name: gateway-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: gateway-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  ZIPKIN_URL: http://zipkin-service:9411
  SPRING_PROFILES_ACTIVE: k8s
kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: { }
          f:CURRENCY_EXCHANGE_URI: { }
      manager: kubectl.exe
      operation: Update
      time: 2021-10-27T17:22:56Z
  name: gateway-service
  namespace: default
